<html>
<head>
    <title>My PHP Page</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
    <h1>About Me</h1>
    <p>This page provides information about me.</p>

    <?php
        // PHP code goes here
        echo "<p>Hello, World! This is generated by PHP.</p>";
    ?>
    <footer>
        <p>&copy; <?php echo date("Y"); ?> My PHP Page</p>
    </footer>
</body>
</html>