<html>
<head>
    <title>My PHP Page</title>
</head>
<body>
    <h1>Welcome to My PHP Page</h1>
    <p>This is a simple PHP page embedded in HTML.</p>

    <?php
        // PHP code goes here
        echo "<p>Hello, World! This is generated by PHP.</p>";
    ?>
</body>
 <footer>
        <p>&copy; <?php echo date("Y"); ?> My PHP Page</p>
    </footer>
</html>